baseUrl = "https://hephaestos.khasegawa.net/"
languageCode = "ja-jp"
defaultContentLanguage = "ja"
title = "khasegawa.net"
copyright = "Copyright Â© 2014-2018 www.khasegawa.net All Rights Reserved."
paginate = 5
theme = "hello-friend"

[params]
  subtitle = "Your site subtitle"

[params.logo]
  logoText = "khasegawa.net"
#   or
#
#   path = "/img/your-example-logo.svg"
#   alt = "Your example logo alt text"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
